### ISSUE TITLE
[BUG/COMPAT] Conflict with Enchancement

### ISSUE THREAD

**Issue by doctor4t** [fewizz/Crawl#35] opened 2022-05-18 14:11 UTC
Enchancement is a mod that revamps enchantments:
https://www.curseforge.com/minecraft/mc-mods/enchancement
https://github.com/MoriyaShiine/enchancement

Enchancement adds an enchantment called "Slide", which allows you to slide (which makes you go crawl) and have an increased crawl speed. However, with this mod installed, it seems that enchantment doesn't work.

Current bugged behaviour: Using the Slide enchantment doesn't make you crawl, and instead makes you sneak after crawling (sliding) for a brief second. Crawling also doesn't have any speed boost when using the crawl keybind or by getting put into a crawl position.

I already discussed this with MoriyaShiine, who announced that the compatibility issue needs to be resolved in this mod as he can't do it in Enchancement.

**Comment by fewizz** [comment] 2024-12-15 13:54
Two years passed, phew..
Can't reproduce, at least in MC 1.21.x; won't fix for previous versions (lazy).

https://github.com/user-attachments/assets/6c6ab16a-369c-4111-85c6-24d8ebc71434

**Closed as completed by fewizz** 2024-12-15 13:54 UTC
Labels: bug
