### ISSUE TITLE
[BUG] Crawling while having levitation makes you suffocate in the block above you

### ISSUE THREAD

**Issue by azeolii** [fewizz/Crawl#65] opened 2023-05-22 18:55 UTC
https://github.com/fewizz/crawl/assets/130517398/3c256d7b-21e2-4f86-9718-cf0292afa1b3

I'm using the latest version of the mod, 0.11.5 (fabric 1.19.4)
(also please ignore my test world in the background)

**Comment by fewizz** [comment] 2024-12-15 09:30
Can't reproduce. Probably was fixed by https://github.com/fewizz/crawl/commit/3f989722a48167c3e9656160650de34e3877bc25

**Closed as completed by fewizz** 2024-12-15 09:30 UTC
Labels: bug
